logging:
  level: "DEBUG"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  console_log: true
  save_to: "./logs/"

reactions: 
  palettes:
    - "ğŸ‘"
    - "â¤ï¸"
    - "ğŸ˜‚"
    - "ğŸ˜®"
    - "ğŸ˜¢"
    - "ğŸ˜¡"