logging:
  level: "DEBUG"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  console_log: true
  save_to: "./logs/"

filepaths:
  accounts: "accounts.json"
  posts: "posts.json"
  tasks: "tasks.json"
  sessions_folder: "sessions/"

reactions_palettes:
  positive:
    - "ğŸ‘"
    - "â¤ï¸"
    - "ğŸ”¥"
  negative:
    - "ğŸ‘"
    - "ğŸ˜¡"
    - "ğŸ¤¬"
    - "ğŸ¤®"
    - "ğŸ’©"
    - "ğŸ¤¡"