logging:
  level: "DEBUG"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  console_log: true
  save_to: "./logs/"

reactions:
  mono:
    - "ğŸ‘"
    - "â¤ï¸"
    - "ğŸ˜‚"
    - "ğŸ˜®"
    - "ğŸ˜¢"
    - "ğŸ˜¡"
  palettes:
    positive:
      - "ğŸ‘"
      - "â¤ï¸"
      - "ğŸ”¥"