logging:
  level: "DEBUG"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  console_log: true
  save_to: "./logs/"

reactions_palettes:
  positive:
    - "ğŸ‘"
    - "â¤ï¸"
    - "ğŸ”¥"
  negative:
    - "ğŸ‘"
    - "ğŸ˜¡"
    - "ğŸ¤¬"
    - "ğŸ¤®"
    - "ğŸ’©"
    - "ğŸ¤¡"