logging:
  level: "DEBUG"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  console_log: true  # Enable logging to console
  save_to: "./logs/"  # Directory to save log files

filepaths:  # File paths for various resources
  accounts: "accounts.json"
  posts: "posts.json"
  tasks: "tasks.json"
  sessions_folder: "sessions/"

reactions_palettes:
  positive:
    - "ğŸ‘"
    - "â¤ï¸"
    - "ğŸ”¥"
  negative:
    - "ğŸ‘"
    - "ğŸ˜¡"
    - "ğŸ¤¬"
    - "ğŸ¤®"
    - "ğŸ’©"
    - "ğŸ¤¡"

delays:
  # Humanization level represents the level at which bot attempts to simulate human behaviour
  # At 0 level (always on) it will only have minimal delays to prevent spamming and getting banned
  # At 1st level (default) it will retrieve message content and wait estimated reading time
  # NYI - At 2nd level it will emulate day-cycle (depending on selected lifestyle), introducing "sessions" of activity, limiting the number of actions per login
  humanisation_level: 1

  connection_retries: 5  # Number of connection retries
  reconnect_delay: 3  # Delay between reconnection attempts
  action_retries: 3  # Number of retries for actions
  action_retry_delay: 2  # Delay between action retries