name: Deploy to VPS

on:
  push:
    branches:
      - main  # triggen on push to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            cd /home/ivand/LikeBot
            
            git fetch --all  # Check if requirements.txt changed
            REQUIREMENTS_CHANGED=$(git diff HEAD origin/main -- requirements.txt | wc -l)
            
            git reset --hard origin/main

            # Install dependencies if requirements.txt changed
            if [ "$REQUIREMENTS_CHANGED" -gt 0 ]; then
              echo "requirements.txt changed, updating dependencies..."
              source venv/bin/activate
              pip install -r requirements.txt
              deactivate
            else
              echo "requirements.txt unchanged, skipping dependency installation"
            fi

            # Installing XDG_RUNTIME_DIR manually for user services
            export XDG_RUNTIME_DIR=/run/user/$(id -u)
            
            # Reloading service as user-unit
            systemctl --user daemon-reload
            systemctl --user restart LikeBot
            systemctl --user status LikeBot --no-pager --lines=20
